FROM node:14
WORKDIR /var/www/html/login-microservice-backend
USER root
COPY ./package.json .
COPY ./yarn.lock .
COPY ./.env .
RUN chown -R node:node /var/www/html
USER node
RUN yarn install --frozen-lockfile
CMD ["bash"]